apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bfe-system

resources:
  - namespace.yaml
  - service-controller-deploy.yaml
  - api-server-configmap.yaml
  - api-server-deploy.yaml
  - bfe-configmap.yaml
  - bfe-deploy.yaml
  - mysql-deploy.yaml
